locafi = ['NFIRE  1\n',
        '\n',
        'FIRE_POS  *\n',
        'Z_CEILING  *\n',
        'PLUME_TYPE CONIC\n',
        '\n',
        'DIAMETER\n',
        '\n',
        '\n',
        '\n',
        '\n',
        'END_DIAM\n',
        '\n',
        'RHR\n',
        '\n',
        '\n',
        '\n',
        '\n',
        'END_RHR\n',]

dummy = [
'Dummy file for McSAFIR\n',
'\n',
'      NNODE     4\n',
'      NDIM    3\n',
'   NDOFMAX    7\n',
'    NCORES    1\n',
'    STATIC   PURE_NR\n',
'     NLOAD    0\n',
'   OBLIQUE    0 \n',
'  COMEBACK 1.0\n',
'   NORENUM\n',
'      NMAT    1\n',
'  ELEMENTS\n',
'      BEAM      1     1\n',
'        NG 2\n',
'    NFIBER    400\n',
'  END_ELEM\n',
'     NODES\n',
        # start of element
'      NODE     1 *\n',
        # end of element
'      NODE     2 *\n',
        # center of element (this is why element is 1D)
'      NODE     3 *\n',
        # orientation (LAX info needed - nota available now) add perpendicular unit vector to node 3
'      NODE     4 *\n',
' FIXATIONS\n',
'   END_FIX\n',
' NODOFBEAM\n',
'safir.tem\n',
' TRANSLATE    1    1\n',
'END_TRANS\n',
'      ELEM   1    1    3    2    4    1\n',
'PRECISION 1.0e-3\n',
'     LOADS\n',
'  END_LOAD\n',
' MATERIALS\n',
'STEELEC3\n',
'           2.10e+11   3.00e-01   2.45e+08  1200.   0.\n',
'      TIME\n',
'      12.0     2400.0\n',
'   ENDTIME\n',
'     EPSTH\n',
'IMPRESSION\n',
' TIMEPRINT\n',
'      60.0     2400.0\n',
'END_TIMEPR\n',
'PRINTREACT\n',
'   PRINTMN\n' 
]
