core = ['NFIRE  1\n',
        '\n',
        'FIRE_POS  *\n',
        'Z_CEILING  *\n',
        'PLUME_TYPE CONIC\n',
        '\n',
        'DIAMETER\n',
        '\n',
        '\n',
        '\n',
        '\n',
        'END_DIAM\n',
        '\n',
        'RHR\n',
        '\n',
        '\n',
        '\n',
        '\n',
        'END_RHR\n']
